# Generated by Django 5.1.1 on 2024-09-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='User',
        ),
    ]
