# Generated by Django 5.1.1 on 2024-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customers_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='customers',
            name='emailid',
            field=models.CharField(max_length=1002),
        ),
    ]
