# Generated by Django 5.1.1 on 2024-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_user_alter_customers_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='emailid',
            field=models.CharField(max_length=1003),
        ),
    ]
