# Generated by Django 5.1.1 on 2024-09-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_customers_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='emailid',
            field=models.CharField(max_length=1001),
        ),
    ]
