# Generated by Django 5.1.1 on 2024-09-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_hide_alter_customers_id_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hide',
        ),
        migrations.AddField(
            model_name='product',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
